#TO DO: ainda precisa ser implementado da forma correta

events {}

http {
    server {
        listen 80;

        location /usuarios {
            proxy_pass http://usuarios:8080;
        }

        location /auth {
            proxy_pass http://auth:8080;
        }
        location /livros {
            proxy_pass http://livros:8080;
        }
    }
}