services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"  # painel web (usuário/senha padrão: guest/guest)
    networks:
      - biblioteca-net

  postgres-livros:
    image: postgres:16-alpine
    container_name: livros-db

    environment:
      POSTGRES_DB: livros_db
      POSTGRES_USER: livros_user
      POSTGRES_PASSWORD: livros_pass

    ports:
      - "5439:5432"

    volumes:
      - livros_data:/var/lib/postgresql/data

    networks:
      - biblioteca-net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U livros_user -d livros_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  livros:
    build:
      context: ./livros
      dockerfile: Dockerfile

    container_name: livros

    depends_on:
      postgres-livros:
        condition: service_healthy
      rabbitmq:
        condition: service_started

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-livros:5432/livros_db
      SPRING_DATASOURCE_USERNAME: livros_user
      SPRING_DATASOURCE_PASSWORD: livros_pass
      AUTH_SERVICE_URL: http://auth:8080
      SPRING_RABBITMQ_HOST: rabbitmq   # <- nome do serviço do RabbitMQ no compose
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

    ports:
      - "8081:8080"

    networks:
      - biblioteca-net


  postgres-emprestimos:
    image: postgres:16-alpine
    container_name: emprestimos-db

    environment:
      POSTGRES_DB: emprestimos_db
      POSTGRES_USER: emprestimos_user
      POSTGRES_PASSWORD: emprestimos_pass

    ports:
      - "5440:5432"

    volumes:
      - emprestimos_data:/var/lib/postgresql/data

    networks:
      - biblioteca-net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emprestimos_user -d emprestimos_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  emprestimos:
    build:
      context: ./emprestimos
      dockerfile: Dockerfile

    container_name: emprestimos

    depends_on:
      postgres-emprestimos:
        condition: service_healthy
      rabbitmq:
        condition: service_started

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-emprestimos:5432/emprestimos_db
      SPRING_DATASOURCE_USERNAME: emprestimos_user
      SPRING_DATASOURCE_PASSWORD: emprestimos_pass
      AUTH_SERVICE_URL: http://auth:8080
      SPRING_RABBITMQ_HOST: rabbitmq   # <- nome do serviço do RabbitMQ no compose
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    
      

    ports:
      - "8085:8080"

    networks:
      - biblioteca-net



  postgres-usuarios:
    image: postgres:16-alpine
    container_name: usuarios-db

    environment:
      POSTGRES_DB: usuarios_db
      POSTGRES_USER: usuarios_user
      POSTGRES_PASSWORD: usuarios_pass

    ports:
      - "5433:5432"

    volumes:
      - usuarios_data:/var/lib/postgresql/data

    networks:
      - biblioteca-net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuarios_user -d usuarios_db"]
      interval: 5s
      timeout: 5s
      retries: 5


  usuarios:
    build:
      context: ./usuarios
      dockerfile: Dockerfile

    container_name: usuarios

    depends_on:
      postgres-usuarios:
        condition: service_healthy
      rabbitmq:
        condition: service_started

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-usuarios:5432/usuarios_db
      SPRING_DATASOURCE_USERNAME: usuarios_user
      SPRING_DATASOURCE_PASSWORD: usuarios_pass
      AUTH_SERVICE_URL: http://auth:8080
      SPRING_RABBITMQ_HOST: rabbitmq   # <- nome do serviço do RabbitMQ no compose
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

    ports:
      - "8082:8080"

    networks:
      - biblioteca-net


  postgres-auth:
    image: postgres:16-alpine
    container_name: auth-db

    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass

    ports:
      - "5434:5432"

    volumes:
      - auth_data:/var/lib/postgresql/data

    networks:
      - biblioteca-net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5


  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile

    container_name: auth

    depends_on:
      postgres-auth:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/auth_db
      SPRING_DATASOURCE_USERNAME: auth_user
      SPRING_DATASOURCE_PASSWORD: auth_pass
      USUARIOS_SERVICE_URL: http://usuarios:8080
      JWT_SECRET: troque-este-segredo-por-uma-chave-forte-de-no-minimo-256-bits-em-producao
      JWT_EXPIRATION_MS: 3600000

    ports:
      - "8083:8080"

    networks:
      - biblioteca-net


  api-gateway:
    image: nginx:latest
    container_name: api-gateway-2

    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro

    ports:
      - "80:80"

    depends_on:
      - usuarios
      - auth

    networks:
      - biblioteca-net


networks:
  biblioteca-net:
    driver: bridge


volumes:
  usuarios_data:
  auth_data:
  livros_data:
  emprestimos_data: