spring.application.name=Emprestimos
spring.datasource.url=jdbc:postgresql://localhost:5440/emprestimos_db
spring.datasource.username=emprestimos_user
spring.datasource.password=emprestimos_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

auth.service.url=http://localhost:8082

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

