spring.application.name=Auth
spring.datasource.url=jdbc:postgresql://localhost:5434/auth_db
spring.datasource.username=auth_user
spring.datasource.password=auth_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

usuarios.service.url=http://localhost:8082
jwt.secret=troque-este-segredo-por-uma-chave-forte-de-no-minimo-256-bits-em-producao
jwt.expiration-ms=3600000
